version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build
      - setup_remote_docker:
          docker_layer_caching: true

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t carwestsam/givemepitch:$CIRCLE_BRANCH .
          docker tag carwestsam/givemepitch:$CIRCLE_BRANCH carwestsam/givemepitch:$TAG
          docker push carwestsam/givemepitch:$CIRCLE_BRANCH
          docker push carwestsam/givemepitch:$TAG
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "/usr/local/bin/redeploy"
